pipeline {
    agent any
    tools {
        maven 'maven-3.9'
        jdk 'JDK-21'
    }
    stages {
        stage('Build') {
            steps {
                dir('user-api') {          // ← go into user-api folder first
                    bat 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('user-api') {          // ← same here
                    bat 'mvn test'
                }
            }
        }
    }
    post {
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
