pipeline {
    agent any
    tools {
        maven 'maven-3.9'
        jdk 'JDK-21'
    }
    stages {
        stage('User API - Build') {
            steps {
                dir('user-api') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }
        stage('User API - Test') {
            steps {
                dir('user-api') {
                    bat 'mvn test'
                }
            }
        }

        stage('Brand Service - Build') {
            steps {
                dir('brand-service') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }
        stage('Brand Service - Test') {
            steps {
                dir('brand-service') {
                    bat 'mvn test'
                }
            }
        }

        stage('Product Service - Build') {
            steps {
                dir('product-service') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }
        stage('Product Service - Test') {
            steps {
                dir('product-service') {
                    bat 'mvn test'
                }
            }
        }
    }
    post {
        success {
            echo 'All microservices built successfully!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
